### PR TITLE
Fix clang build with casts.

### PR DESCRIPTION
**Pull request by orbea**
Fixes the build with `clang-8.0.0` by using static casts as suggested by the compiler.

Same issue and solution as PR  https://github.com/libretro/blueMSX-libretro/pull/94.

Updating the core with changes from upstream mednafen would probably also help, but that is a more involved process than I feel confident in doing. It can always be done later after a quick fix.

### CODE REVIEW

**Comment by orbea** [comment]
travis failure is unrelated.

**Comment by twinaphex** [comment]
I don't think it's a good idea to get further into C++ here, if anything ,the core should become more completely C-based.

**Comment by orbea** [comment]
@twinaphex That is already beyond the scope of this PR, this is a c++ file already and if someone wants to change that then that should be done in a followup PR.

**Comment by funbars** [comment]
Would clang accept plain typecast?
```
{ &(gfx->S1SO_H), static_cast<uint32_t>(SF_IS_BOOL(&(gfx->S1SO_H)) ? 1 : sizeof(gfx->S1SO_H)), 0x80000000 | (SF_IS_BOOL(&(gfx->S1SO_H)) ? 0x08000000 : 0), "S1SO_H" },

-->

{ &(gfx->S1SO_H), (uint32_t)(SF_IS_BOOL(&(gfx->S1SO_H)) ? 1 : sizeof(gfx->S1SO_H)), 0x80000000 | (SF_IS_BOOL(&(gfx->S1SO_H)) ? 0x08000000 : 0), "S1SO_H" },
```

**Comment by orbea** [comment]
Yes, I updated the PR.

**Pull request merged**
