### PR TITLE
libretro: Add install and uninstall make targets

### PR DESCRIPTION
**Pull request by Kekun**
So we can properly install the core system wide.

### CODE REVIEW

**Comment by twinaphex** [comment]
Only issue I can see with this is that it's very Unix-specific and that it wouldn't do you much good on Windows. 

I can overlook that though if it's for GNOME Games convenience or whatever. Personally I'm not going to use it but I'm fine with if it's necessary for GNOME Games.

**Comment by twinaphex** [comment]
The thing that I see as an issue though on installing cores like this in system directories is that you wouldn't be able to easily upgrade them online. That is why we with RetroArch never install libretro cores inside these system directories.

But it's all up to you. If you prefer package management and manual tagging of new cores through packages, I guess that could work for your usecase. It's just again something I very much try to avoid doing with RetroArch, I prefer that most get their cores all from the same place and so that we are assured everybody is on the same git revision, this will become especially more important now with netplay where in order for netplay to work, the core version has to be exactly the same.

**Comment by Kekun** [comment]
This fix is a convenience for installing the libretro cores system wide and to distribute them in Linux distros and Flatpak. AFAIK some Linux distros like Arch and openSUSE started distributing the cores that way when we were trying to do something similar for Games, so we decided to do it the Linux distros' way. Clearly it's not for every Libretro client but we prefer that way for Games. :) It shouldn't harm RA and libretro-super in any way.

Some other cores have these rules, like bsnes, Gambatte and Nestopia.

**Comment by twinaphex** [comment]
Alright, understood. I want to be accomodating so here goes.

**Comment by orbea** [comment]
@Kekun You want `rm -f` in uninstall targets.

**Pull request merged**
