### PR TITLE
color correction (32-bpp)

### PR DESCRIPTION
**Pull request by f21red**

### CODE REVIEW

**Comment by negativeExponent** [comment]
for performance reasons, especially on slow devices, thought RA was to use 16 if possible. seems like 32bit is being hardcoded as the norm in this. isn't this color correction unavailable using shaders or a combination that edits params?

**Comment by f21red** [comment]
I couldn't replicate these pixel corrections using shaders so thought it would be useful, or for those who don't have hardware shader support. I don't want to eat more performance out of slower devices so I'll shut this down.

**Comment by tryal-star** [comment]
I think the 32-bpp code is good to add, if it isn't forced on everyone by default. Maybe for windows (msvc2017, mingw) or linux it'd make sense.

And the color modifier is not bad either. But it might work better as a standalone shader; it is just a 32 entry lookup table per color channel.

**Comment by tryal-star** [comment]
It was simple to port. Here's the result.
https://raw.githubusercontent.com/tryal-star/glsl-shaders/color_curves/color-curves.glsl

**Pull request closed without merging**
