### PR TITLE
save fix

### PR DESCRIPTION
**Pull request by HerbFargus**

### CODE REVIEW

**Comment by fr500** [comment]
That doesn't really fix anything...

**Comment by HerbFargus** [comment]
The savestates work fine but the in game saves save in the system directory, this makes them default to the rom directory in the same place as the save states

**Comment by fr500** [comment]
It's saving in the same directory for me

**Comment by fr500** [comment]
Savestates are not saved by the core. They are always saved to whatever you have set as savestate dir because the frontend saves them. 
In-game saves may or not be saved by the frontend. In any case the code looks correct here.

If save directory is defined (the frontend must define this) it's setting it to RETRO_SAVE_DIRECTORY, otherwise it's saving in retro_base_dir which is in turn the SYSTEM dir.

If there is an error it would be the last part, base directory should be the rom dir. Not the system dir but fixing that would be more involved than this since base directory is being used to lookup for the firmware, I'll fix this later but this pull is not correct.

**Comment by HerbFargus** [comment]
yeah I guess you're right, the code behaves a bit differently with ngp than it does with the others, but yes the `savefile_directory` setting is still broken as you're aware.

I apologise for the noise.

**Comment by fr500** [comment]
nope, the savefile_directory setting is working correctly on all the platforms I tested and it's saving to the correct location, I tested:

- No save directory defined -> saves to system dir (correct by the code)
- Save directory defined -> saves to save dir
- No save directory defined sorting enabled -> saves to system dir (correct by the code)
- Save directory defined -> saves to save dir \ Mednafen NeoPop\

It's correct, the only problem I see is it falling back to system dir instead of the rompath.
The fix is wrong in the other repos too, I'll fix them all up by the weekend.

**Comment by HerbFargus** [comment]
Appreciated. I'll be happy to test any changes just to make sure that they are working as intended :)

**Pull request closed without merging**
